homeassistant:
  name: GENISYS
  latitude: !secret gps_home_lat
  longitude: !secret gps_home_lon
  elevation: 95
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Warsaw
  packages: !include_dir_named packages/
  external_url: !secret external_url
  internal_url: !secret internal_url
  auth_providers:
  - type: homeassistant
http:
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_priv
lovelace:
  mode: yaml
  resources: !include configi/love_resource.yaml
discovery:
  ignore:
  - yeelight
google:
  client_id: !secret g_cal_client_id
  client_secret: !secret g_cal_key
tts:
- platform: google_translate
  language: "pl"
  time_memory: 300
config:
conversation:
hassio:
mobile_app:
sun:
system_health:
updater:
uilogs:
wake_on_lan:
############# includy
automation: !include_dir_merge_list automations/
browser_mod: !include configi/browser_mod.yaml
frontend: !include configi/frontend.yaml
google_assistant: !include configi/google.yaml
history:
  include: !include configi/log_include.yaml
influxdb: !include configi/influx.yaml
logbook:
  include: !include configi/log_include.yaml
mqtt: !include configi/mqtt.yaml
panel_iframe: !include configi/iframe.yaml
recorder: !include configi/recorder.yaml
script: !include_dir_merge_named scripts/
sensor: !include configi/sensors.yaml
zone: !include configi/zones.yaml