title: Home
button_card_templates: !include lovelace/tmpl_button_card.yaml
views:
- !include lovelace/love_main.yaml
- !include lovelace/love_cctv.yaml
- !include lovelace/love_remote.yaml
- !include lovelace/love_koninko.yaml
- !include lovelace/love_admin.yaml
