device_tracker:
- platform: nmap_tracker
  track_new_devices: false
  hosts:
  - !secret ip_chef
  - !secret ip_johanna
  - !secret ip_googy
  - !secret ip_boogy
  - !secret ip_tic
  - !secret ip_little_screen
  - !secret ip_xbone
  - !secret ip_narnia
  - !secret ip_lgtv
  - !secret ip_lestaro
  - !secret ip_chromecast
  - !secret ip_kamera
  home_interval: 5
  scan_options: "-F --host-timeout 15s"
group:
  gr_onoff: 
    entities:
    - device_tracker.lgwebostv
    - device_tracker.lgwebostvwifi
webostv:
  host: !secret ip_lgtv
  name: LG TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret mac_lgtv
  customize:
    sources:
    - Live TV
    - Netflix
    - YouTube
    - YouTube Kids
#media_player:
#- platform: kodi
#  host: !secret ip_narnia