homeassistant:
  customize:
    sensor.mokry:
      friendly_name: "Średnia wilgotność w domu"
      icon: mdi:water-percent
    sensor.tempy:
      friendly_name: "Średnia temperatura w domu"
      icon: mdi:temperature-celsius
group:
  gr_weather: ### ogolnie pogoda
    entities:
    - sensor.nowa_pora
    - sensor.moon
    - sun.sun
  gr_climat_srednia:
    entities:
    - sensor.mokry
    - sensor.tempy
  gr_temp: ### czujniki temperatury w calym domu
    entities:
    - sensor.salon_temperature
    - sensor.bear_temperature
    - sensor.bee_temperature
    - sensor.kitchen_temperature
    - sensor.bath_temperature
    - sensor.wc_temperature
    - sensor.lamus_temperature
  gr_humi: ### czujniki wilgotnosci w calym domu
    entities:
    - sensor.salon_humidity
    - sensor.bear_humidity
    - sensor.bee_humidity
    - sensor.kitchen_humidity
    - sensor.bath_humidity
    - sensor.wc_humidity
    - sensor.lamus_humidity
sensor:
- platform: min_max
  name: "Mokry"
  type: mean
  round_digits: 1
  entity_ids:
  - sensor.bear_humidity
  - sensor.salon_humidity
  - sensor.bee_humidity
- platform: min_max
  name: "Tempy"
  type: mean
  round_digits: 1
  entity_ids:
  - sensor.bear_temperature
  - sensor.salon_temperature
  - sensor.bee_temperature
- platform: moon
- platform: time_date
  display_options: "date_time"

#################################################
###             PORA DNIA                     ###
#################################################

- platform: template
  sensors:
    nowa_pora:
      friendly_name: "Nowa pora dnia"
      value_template: >-
        {% set teraz = now().hour*60+now().minute %}
        {# #################### pory dnia -#}
        {%- set t_pory = {
          0:{0:'# info ##########', 1:'# nazwa #########', 2:'# start #########'},
          1:{0:'# 06:40 - 07:30 #', 1:'ranek',             2:6*60+40},
          2:{0:'# 07:30 - zach. #', 1:'dzień',             2:7*60+30},
          3:{0:'# 16:00 - 19:00 #', 1:'zmierzch',          2:16*60+0},
          4:{0:'# 19:00 - 19:40 #', 1:'wieczór',           2:19*60+0},
          5:{0:'# 19:40 - 23:00 #', 1:'tryb_spania',       2:19*60+40},
          6:{0:'# 23:00 - 01:00 #', 1:'noc',               2:23*60+0},
          7:{0:'# 01:00 - 05:00 #', 1:'sen',               2:1*60+0},
          8:{0:'# 05:00 - 06:40 #', 1:'none',              2:5*60+0}
        } -%}
        {# #################### warunki -#}
        {%- for t in range(1, t_pory|length) -%}
          {%- set n = 1 if loop.last else t + 1 -%}
          {%- set t_start = t_pory[t][2] -%}
          {%- set t_stop = t_pory[n][2] -%}
          {%- set t_temp = 1440 if (t_stop<t_start) else 0 -%}
          {%- set t_stop = t_stop + t_temp - 1 -%}
          {%- set teraz = teraz + t_temp if ((teraz < t_start) and (teraz < t_stop)) else teraz %}
          {{ t_pory[t][1] if ((teraz >= t_start) and (teraz <= t_stop)) }}
        {% endfor %}
      icon_template: >-
        {# #################### konfig ikon -#}
        {%- set t_ikony = {
          'ranek':      'mdi:weather-sunset-up',
          'dzień':      'mdi:weather-sunny',
          'zmierzch':   'mdi:weather-sunset',
          'wieczór':    'mdi:weather-sunset-down',
          'tryb_spania':'mdi:brightness-1',
          'noc':        'mdi:brightness-2',
          'sen':        'mdi:weather-night'
        } -%}
        {{ t_ikony[states('sensor.nowa_pora')] if states('sensor.nowa_pora') in t_ikony.keys() else 'mdi:weather-sunny' }}
      attribute_templates:
        tod_value: >-
          {# #################### pora dnia liczbowo -#}
          {%- set t_numery = {
            'ranek': 1,
            'dzień': 2,
            'zmierzch':3,
            'wieczór': 4,
            'tryb_spania': 5,
            'noc': 6,
            'sen': 7,
            'none': 8
          } -%}
          {{ t_numery[states('sensor.nowa_pora')] if states('sensor.nowa_pora') in t_numery.keys() else '0' }}
    nr_dnia:
      value_template: '{{ states.sensor.nowa_pora.attributes.tod_value }}'
binary_sensor:
- platform: template
  sensors:
    weekend:
      value_template: >
        {% set t_today = states('sensor.time_date')[12:] %}
        {% set t_holiday = ('01-01', '01-06', '05-01', '05-03', '08-15', '11-01', '11-11', '12-24', '12-25', '12-26') %}
        {{ (((now().isoweekday() == 5) and (now().hour >= 15)) or ((now().isoweekday() == 7) and (now().hour < 22)) or now().isoweekday() == 6 or (t_today in t_holiday)) }}
      icon_template: "{{ 'mdi:calendar-heart' if is_state('binary_sensor.0_cfg_weekend', 'on') else 'mdi:calendar-month' }}"