  #################### robimy snapszota i wysyłamy na dropboxa
sensor:
- platform: version
  name: sns_ha_version
automation: 
- alias: snapshot
  id: snapshot_partial
  initial_state: true
  trigger:
  - platform: time
    at: "04:00:00"
  action:
  - service: hassio.snapshot_partial
    data_template:
      name: "{{ ('auto_',now().strftime('%Y%m%d'),'_',states.sensor.sns_ha_version.state)|join() }}"
      password: !secret http_password
      addons:
        - 7be23ff5_dropbox_sync
        - 7ad98f9c_zigbee2mqtt
        - a0d7b954_influxdb
        - a0d7b954_motioneye
        - a0d7b954_sonweb
        - core_duckdns
      folders:
        - ssl
        - media
        - homeassistant
  - delay: "00:15:00"
  - service: hassio.addon_stdin
    data_template:
      addon: "7be23ff5_dropbox_sync"
      input: {"command":"upload"}
