homeassistant:
device_tracker:
- platform: nmap_tracker
  track_new_devices: false
  hosts:
  - !secret ip_chef
  - !secret ip_johanna
  - !secret ip_googy
  - !secret ip_boogy
  - !secret ip_tic
  - !secret ip_kitchen_display
  - !secret ip_xbone
  - !secret ip_narnia
  - !secret ip_lgtv
  - !secret ip_lestaro
  - !secret ip_chromecast
  - !secret ip_kamera
  home_interval: 5
  scan_options: "-F --host-timeout 15s"
group:
  gr_onoff: 
    entities:
    - media_player.lg_tv
    - device_tracker.lgwebostv
    - device_tracker.lgwebostvwifi
    - device_tracker.chromecast
    - device_tracker.ipkamera
    - device_tracker.lestaro
    - device_tracker.narniapi3
    - device_tracker.samsungtv
    - device_tracker.xboxone
    - device_tracker.googy
    - device_tracker.tic
    - device_tracker.boogy
    - device_tracker.kitchen_display
webostv:
  host: !secret ip_lgtv
  name: LG TV
  # filename: webostv.conf
  # timeout: 5
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret mac_lgtv
  customize:
    sources:
    - Live TV
    - Netflix
    - YouTube
    - YouTube Kids
media_player:
- platform: kodi
  host: !secret ip_narnia
cast:
  media_player:
  - host: !secret ip_chromecast
    mac: !secret mac_chromecast
  - host: !secret ip_googy
    mac: !secret mac_googy
  - host: !secret ip_boogy
    mac: !secret mac_boogy
  - host: !secret ip_tic
    mac: !secret mac_tic
  - host: !secret ip_kitchen_display
    mac: !secret mac_kitchen_display