automation:
- alias: btn_salon_single # lampa w salonie
  trigger:
    platform: state
    entity_id: sensor.btn_salon_click
    to: "single"
  condition:
    condition: state
    entity_id: group.gr_who
    state: "home"
  action:
  - service: light.toggle
    entity_id: light.lampa_w_salonie
- alias: btn_salon_double # plafon 
  trigger:
    platform: state
    entity_id: sensor.btn_salon_click
    to: "double"
  condition:
    condition: state
    entity_id: group.gr_who
    state: "home"
  action:
  - service: light.toggle
    entity_id: light.plafon
- alias: tradfri_bright # lampa w salonie
  trigger:
    platform: state
    entity_id: sensor.tradfri_one_action
    to: "brightness_up_click"
  action:
  - service: light.toggle
    entity_id: light.lampa_w_salonie
- alias: tradfri_dimm # plafon
  trigger:
    platform: state
    entity_id: sensor.tradfri_one_action
    to: "brightness_down_click"
  action:
  - service: light.toggle
    entity_id: light.plafon
- alias: tradfri_left # swiatlo u MB
  trigger:
    platform: state
    entity_id: sensor.tradfri_one_action
    to: "arrow_left_click"
  action:
  - service: light.toggle
    entity_id: light.yl_maja
- alias: tradfri_right # swiatlo u BB
  trigger:
    platform: state
    entity_id: sensor.tradfri_one_action
    to: "arrow_right_click"
  action:
  - service: light.toggle
    entity_id: light.yl_bernard