homeassistant:
  customize:
    ################################ ŚWIATŁA ################
    light.yl_bernard:
      friendly_name: "Sypialnia Bernard"
      icon: mdi:track-light
    light.yl_maja: #######
      friendly_name: "Sypialnia Maja"
      icon: mdi:lamp
    light.yl_plafon1:
      friendly_name: "Plafon 1"
      icon: mdi:lamp
    light.yl_plafon2: #####
      friendly_name: "Plafon 2"
    light.lampa_w_salonie:
      icon: mdi:ceiling-light
    light.yl_wc:
      friendly_name: "WC"
      icon: mdi:human-male-female
    light.yl_korytarz:
      friendly_name: "Korytarz"
      icon: mdi:shoe-print

yeelight:
  devices:
    192.168.2.51: #yl1 salon
      name: yl1
      transition: 1000
      use_music_mode: False
      save_on_change: True
    192.168.2.52: #yl2 salon
      name: yl2
      transition: 1000
      use_music_mode: False
      save_on_change: True
    192.168.2.53: #yl3 salon
      name: yl3
      transition: 1000
      use_music_mode: False
      save_on_change: True
    192.168.2.54: #Bernard
      name: yl_bernard
      transition: 1000
      use_music_mode: False
      save_on_change: True
    192.168.2.55: #Maja
      name: yl_maja
      transition: 1000
      use_music_mode: False
      save_on_change: True
    192.168.2.56: #yl plafon1
      name: yl_plafon1
      transition: 1000
      use_music_mode: False
      save_on_change: True
    192.168.2.57: #yl plafon2
      name: yl_plafon2
      transition: 1000
      save_on_change: True
    192.168.2.58: #yl wc
      name: yl_wc
      transition: 1000
      use_music_mode: False
      save_on_change: False
    192.168.2.59: #yl korytarz
      name: yl_korytarz
      transition: 1000
      use_music_mode: False
      save_on_change: False
light:
- name: Lampa w salonie
  platform: group
  entities:
  - light.yl1
  - light.yl2
  - light.yl3
- name: Plafon
  platform: group
  entities:
  - light.yl_plafon1
  - light.yl_plafon2
automation:
- alias: wc_light
  mode: restart
  trigger:
  - platform: state
    entity_id: binary_sensor.drzwi_wc_contact
    to: "on"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('group.gr_who', 'home') and is_state('input_boolean.tryb_spania', 'off') and states('sensor.nr_dnia') <= '4' }}"  ######and 22 >= now().hour >= 7
      sequence:
        - service: script.run_scene
          data:
            t_config: '---------2'
        - delay: "00:03:00"
        - service: script.run_scene
          data:
            t_config: '---------0'
    - conditions: 
      - condition: template
        value_template: "{{ is_state('group.gr_who', 'home') and is_state('input_boolean.tryb_spania', 'on') or is_state('group.gr_who', 'home') and states('sensor.nr_dnia') > '4' }}"
      sequence:
      - service: script.run_scene
        data:
          t_config: '---------4'
      - delay: "00:03:00"
      - service: script.run_scene
        data:
          t_config: '---------0'
- alias: hw_light # korytarz
  mode: restart
  trigger:
  - platform: state
    entity_id: binary_sensor.ruch_korytarz_occupancy
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state('group.gr_who', 'home') and is_state('binary_sensor.ruch_korytarz_occupancy', 'on') and is_state('input_boolean.tryb_spania', 'off') and states('sensor.nr_dnia') <= '4' }}"
      sequence:
      - service: script.run_scene
        data:
          t_config: '------2'
    - conditions:
      - condition: template
        value_template: "{{ is_state('group.gr_who', 'home') and is_state('binary_sensor.ruch_korytarz_occupancy', 'on') and states('sensor.nr_dnia') > '4' }}"
      sequence:
      - service: script.run_scene
        data:
          t_config: '------4'
    - conditions:
      - condition: template
        value_template: "{{ is_state('binary_sensor.ruch_korytarz_occupancy', 'off') }}"
      sequence:
      - service: script.run_scene
        data:
          t_config: '------0'
- alias: kt_light # kuchnia
  mode: restart
  trigger:
  - platform: state
    entity_id: binary_sensor.ruch_kuchnia_occupancy
  action:
  - choose:
    - conditions: # do wieczora ON
      - condition: template
        value_template: "{{ is_state('group.gr_who', 'home') and is_state('binary_sensor.ruch_kuchnia_occupancy', 'on') and states('sensor.nr_dnia') < '6' }}"
      sequence:
      - service: light.turn_on
        entity_id: light.ledy_w_kuchni
    - conditions: # do wieczora OFF
      - condition: template
        value_template: "{{ is_state('binary_sensor.ruch_kuchnia_occupancy', 'off') and states('sensor.nr_dnia') <= '6' }}"
      sequence:
      - service: light.turn_off
        entity_id: light.ledy_w_kuchni
    - conditions: # w nocy ON
      - condition: template
        value_template: "{{ is_state('group.gr_who', 'home') and is_state('binary_sensor.ruch_kuchnia_occupancy', 'on') and states('sensor.nr_dnia') >= '6' }}"
      sequence:
      - service: script.run_scene
        data:
          t_config: '----4-'
    - conditions: # w nocy OFF
      - condition: template
        value_template: "{{ is_state('binary_sensor.ruch_kuchnia_occupancy', 'off') and states('sensor.nr_dnia') >= '6' }}"
      sequence:
      - service: script.run_scene
        data:
          t_config: '----0-'
- alias: budzik
  trigger:
  - platform: time
    at: "06:53:00"
  action:
    - service: script.run_scene
      data:
        t_config: '-505'
    - delay: "00:00:30"
    - service: script.run_scene
      data:
        t_config: '-6-6'  
    - delay: "00:00:30"
    - service: script.run_scene
      data:
        t_config: '-7-7'
    - delay: "00:03:00"
    - service: script.run_scene
      data:
        t_config: '-0-0'