  #################### robimy snapszota i wysyłamy na dropboxa
sensor:
- platform: version
  name: sns_ha_version
automation: 
- alias: snapshot
  trigger:
  - platform: time
    at: "04:00:00"
  action:
  - service: hassio.snapshot_full
    data_template:
      name: "{{ ('auto_',now().strftime('%Y%m%d'),'_rpi3_',states.sensor.sns_ha_version.state)|join() }}"
      password: !secret http_password
  - delay: '00:15:00'
  - service: hassio.addon_stdin
    data_template:
      addon: "7be23ff5_dropbox_sync"
      input: {"command":"upload"}