automation:
- alias: btn_salon_single # lampa w salonie
  trigger:
    platform: state
    entity_id: sensor.salon_btn1_click
    to: "single"
  condition:
    condition: state
    entity_id: group.gr_who
    state: "home"
  action:
  - service: light.toggle
    entity_id: light.lampa_w_salonie
- alias: btn_salon_double # plafon 
  trigger:
    platform: state
    entity_id: sensor.salon_btn1_click
    to: "double"
  condition:
    condition: state
    entity_id: group.gr_who
    state: "home"
  action:
  - service: light.toggle
    entity_id: light.plafon
- alias: tradfri_bright # lampa w salonie
  trigger:
    platform: state
    entity_id: sensor.salon_trad1_action
    to: "brightness_up_click"
  action:
  - service: light.toggle
    entity_id: light.lampa_w_salonie
- alias: tradfri_dimm # plafon
  trigger:
    platform: state
    entity_id: sensor.salon_trad1_action
    to: "brightness_down_click"
  action:
  - service: automation.trigger
    entity_id: automation.plafon_light
- alias: tradfri_left # swiatlo u MB
  trigger:
    platform: state
    entity_id: sensor.salon_trad1_action
    to: "arrow_left_click"
  action:
  - service: automation.trigger
    entity_id: automation.mj_light
- alias: tradfri_right # swiatlo u BB
  trigger:
    platform: state
    entity_id: sensor.salon_trad1_action
    to: "arrow_right_click"
  action:
  - service: automation.trigger
    entity_id: automation.bb_light
- alias: tradfri_middle
  trigger:
    platform: state
    entity_id: sensor.salon_trad1_action
    to: "toggle"
  action:
  - service: automation.trigger
    entity_id: automation.middle

################################### poniżej do usuniecia
- alias: praca w kuchnia
  trigger:
  - platform: state
    entity_id: input_boolean.tryb_praca_w_kuchni
    to: "on"
  action:
  - service: notify.mobile_app_chef_xl
    data:
      message: 'Hej Chef! dog'
      data:
        image: "https://www.sciencemag.org/sites/default/files/styles/article_main_image_-_1280w__no_aspect_/public/dogs_1280p_0.jpg"
        ttl: 0
        priority: high
        tag: tag
        actions:
        - action: "alarm" # The key you are sending for the event
          title: "Title" # The button title
        - action: "URI" # Must be set to URI if you plan to use a URI
          title: "Open Url"
          uri: "https://google.com" # URL to open when action is selected, can also be a lovelace view/dashboard
        - action: "URI" # Must be set to URI if you plan to open an application
          title: "Open Twitter"
          uri: "app://com.twitter.android"
  - service: script.run_scene
    data:
      t_config: '---'
