automation:
- alias: btn_salon_single # lampa w salonie
  trigger:
    platform: state
    entity_id: sensor.btn_salon_click
    to: "single"
  condition:
    condition: state
    entity_id: group.gr_who
    state: "home"
  action:
  - service: light.toggle
    entity_id: light.lampa_w_salonie
- alias: btn_salon_double # plafon 
  trigger:
    platform: state
    entity_id: sensor.btn_salon_click
    to: "double"
  condition:
    condition: state
    entity_id: group.gr_who
    state: "home"
  action:
  - service: light.toggle
    entity_id: light.plafon
- alias: tradfri_bright # lampa w salonie
  trigger:
    platform: state
    entity_id: sensor.tradfri_one_action
    to: "brightness_up_click"
  action:
  - service: light.toggle
    entity_id: light.lampa_w_salonie
- alias: tradfri_dimm # plafon
  trigger:
    platform: state
    entity_id: sensor.tradfri_one_action
    to: "brightness_down_click"
  action:
  - service: light.toggle
    entity_id: light.plafon
- alias: tradfri_left # swiatlo u MB
  trigger:
    platform: state
    entity_id: sensor.tradfri_one_action
    to: "arrow_left_click"
  action:
  - service: light.toggle
    entity_id: light.yl_maja
- alias: tradfri_right # swiatlo u BB
  trigger:
    platform: state
    entity_id: sensor.tradfri_one_action
    to: "arrow_right_click"
  action:
  - service: light.toggle
    entity_id: light.yl_bernard
- alias: praca w kuchnia
  trigger:
  - platform: state
    entity_id: input_boolean.tryb_praca_w_kuchni
    to: "on"
  action:
  - service: notify.mobile_app_chef_xl
    data:
      message: 'Hej Chef!'
  - service: script.run_scene
    data:
      t_config: '---'
script:
  kuchnia_poczatek_pracy:
    sequence:
    - service: light.turn_on
      data:
        entity_id: light.ledy_w_kuchni
    - service: automation.turn_off
      data:
        entity_id: automation.kt_light
    - service: notify.mobile_app_chef2xl
      data:
        message: 'Hej Chef!'
  kuchnia_koniec_pracy:
    sequence:
    - service: automation.turn_on
      data:
        entity_id: automation.kt_light