homeassistant:
  # customize:
input_boolean:
  tryb_spania:
    name: Tryb spania
    initial: off
    icon: mdi:sleep
  tryb_kinowy:
    name: Tryb kinowy
    initial: off
    icon: mdi:theater
  tryb_xbox: 
    name: Tryb gry
    initial: off
    icon: mdi:microsoft-xbox
  tryb_praca_w_kuchni:
    name: Praca w kuchni
    initial: off
    icon: mdi:stove
input_select:
  isl_pora_dnia:
    name: isl_pora_dnia
    options:
    - dawn
    - day
    - dusk
    - night
    - tryb_spania
    # - sen
    # - tryb_kinowy
    # - xbox
automation:
  - alias: au_isl_pora_dnia_sceny
    trigger:
      - platform: state
        entity_id: input_select.isl_pora_dnia
    action:
      - condition: state
        entity_id: group.gr_who
        state: home
      - service: scene.turn_on
        data_template:
          entity_id: "{{ 'scene.sc_{}'.format(states.input_select.isl_pora_dnia.state) }}"
  - alias: au_automatyczna_pora_dnia
    trigger:
      - platform: state
        entity_id: sensor.pora_dnia
      - platform: state
        entity_id: input_boolean.tryb_spania
        to: "off"
    action:
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: state
            entity_id: input_boolean.tryb_spania
            state: "off"
          - condition: state
            entity_id: input_boolean.tryb_kinowy
            state: "off"
          - condition: state
            entity_id: input_boolean.tryb_xbox
            state: "off"
        - condition: and
          conditions:
          - condition: state
            entity_id: input_boolean.tryb_spania
            state: "on"
          - condition: state
            entity_id: sensor.pora_dnia
            state: "dawn"
      - service: input_select.select_option
        data_template:
          entity_id: input_select.isl_pora_dnia
          option: >
            {% if  (states.sensor.pora_dnia.state == "night") %}
            night
            {%-elif (states.sensor.pora_dnia.state == "dawn") %}
            dawn
            {%-elif (states.sensor.pora_dnia.state == "dusk") %}
            dusk
            {% else %}
            day
            {% endif %}
      - service: input_boolean.turn_off
        entity_id: input_boolean.tryb_spania