homeassistant:
  customize:
    ################################ ŚWIATŁA ################
    light.yl_bernard:
      friendly_name: "Sypialnia Bernard"
      icon: mdi:track-light
    light.yl_maja: #######
      friendly_name: "Sypialnia Maja"
      icon: mdi:lamp
    light.yl_plafon1:
      friendly_name: "Plafon 1"
      icon: mdi:lamp
    light.yl_plafon2: #####
      friendly_name: "Plafon 2"
    light.lampa_w_salonie:
      icon: mdi:ceiling-light
    light.yl_wc:
      friendly_name: "WC"
      icon: mdi:human-male-female
    light.yl_korytarz:
      friendly_name: "Korytarz"
      icon: mdi:shoe-print
################################ SCENY ################
### Bernard
    scene.bb_tryb_spania:
      friendly_name: "Bernard - tryb spania"
      icon: mdi:bed
    scene.bb_tryb_normalny:
      friendly_name: "Bernard - tryb normalny"
      icon: mdi:bed
### Maja
    scene.mb_tryb_spania:
      friendly_name: "Maja - tryb spania"
      icon: mdi:bed
    scene.mb_tryb_normalny:
      friendly_name: "Maja - tryb normalny"
      icon: mdi:bed
### SALON
    scene.sl_tryb_normalny: #salon
      friendly_name: "Salon - tryb normalny"
      icon: mdi:ceiling-light
    scene.plafon_tryb_normalny:
      friendly_name: "Plafon - tryb normalny"
      icon: mdi:bed
    scene.plafon_tryb_red:
      friendly_name: "Plafon - tryb nocny"
      icon: mdi:bed
### Korytarz Hallway
    scene.hw_tryb_normalny:
      friendly_name: "Korytarz - tryb normalny"
      icon: mdi:ceiling-light
    scene.hw_tryb_red:
      friendly_name: "Korytarz - tryb nocny"
      icon: mdi:ceiling-light
### KUCHNIA
### WC
    scene.wc_tryb_normalny:
      friendly_name: "WC - tryb normalny"
      icon: mdi:ceiling-light
    scene.wc_tryb_red:
      friendly_name: "WC - tryb noc"
      icon: mdi:ceiling-light

yeelight:
  devices:
    192.168.2.51:
      name: yl1 # SALON
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: True #(defaults to True)
    192.168.2.52:
      name: yl2 # SALON
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: True #(defaults to True)
    192.168.2.53:
      name: yl3 # SALON
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: True #(defaults to True)
    192.168.2.54:
      name: yl_bernard #Bernard
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: True #(defaults to True)
    192.168.2.55:
      name: yl_maja #sypialnia chef
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: True #(defaults to True)
    192.168.2.56:
      name: yl_plafon1 #sypialnia JB
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: True #(defaults to True)
    192.168.2.57:
      name: yl_plafon2
      transition: 1000
      save_on_change: True
    192.168.2.58:
      name: yl_wc
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
    192.168.2.59:
      name: yl_korytarz
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
light:
  - platform: group
    name: Lampa w salonie
    entities:
    - light.yl1
    - light.yl2
    - light.yl3
  - platform: group
    name: Plafon
    entities:
    - light.yl_plafon1
    - light.yl_plafon2
automation:
  - alias: au_tryb_spania
    trigger:
    - platform: time
      at: "19:50:00"
    - platform: state
      entity_id: input_boolean.tryb_spania
      to: "on"
    action:
    - condition: or
      conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: group.gr_who
          state: "home"
        - condition: state
          entity_id: input_boolean.tryb_spania
          state: "off"
        - condition: time
          before: "19:51:00"
      - condition: and
        conditions:
        - condition: state
          entity_id: group.gr_who
          state: "home"
        - condition: state
          entity_id: input_boolean.tryb_spania
          state: "on"
    - service: input_select.select_option
      data:
        entity_id: input_select.isl_pora_dnia
        option: tryb_spania
    - service: input_boolean.turn_on
      entity_id: input_boolean.tryb_spania
  - alias: wc_light
    mode: restart
    trigger:
    - platform: state
      entity_id: binary_sensor.drzwi_wc_contact
      to: "on"
    action:
    - choose:
      - conditions:
        - condition: and
          conditions:
          - condition: state
            entity_id: input_boolean.tryb_spania
            state: "off"
          - condition: time
            after: "07:00:00"
            before: "22:59:00"
        sequence:
        - service: scene.turn_on
          entity_id: scene.wc_tryb_normalny
        - delay: "00:03:00"
        - service: light.turn_off
          entity_id: light.yl_wc
      - conditions: 
        - condition: or
          conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: input_select.isl_pora_dnia
              state: "tryb_spania"
            - condition: state
              entity_id: light.yl_wc
              state: "off"
          - condition: time
            after: "23:00:00"
            before: "06:59:00"
        sequence:
        - service: scene.turn_on
          entity_id: scene.wc_tryb_red
        - delay: "00:03:00"
        - service: light.turn_off
          entity_id: light.yl_wc
      default:
      - service: light.turn_off
        entity_id: light.yl_wc
# korytarz
  - alias: hw_light
    mode: restart
    trigger:
    - platform: state
      entity_id: binary_sensor.ruch_korytarz_occupancy
      to: "on"
    action:
    - choose:
      - conditions:
        - condition: and
          conditions:
          - condition: state
            entity_id: group.gr_who
            state: "home"
          - condition: state
            entity_id: input_boolean.tryb_spania
            state: "off"
          - condition: state
            entity_id: light.yl_korytarz
            state: "off"
          - condition: time
            after: "08:00:00"
            before: "23:59:00"
        sequence:
        - service: scene.turn_on
          entity_id: scene.hw_tryb_normalny
      - conditions:
        - condition: and
          conditions:
          - condition: state
            entity_id: group.gr_who
            state: "home"
          - condition: state
            entity_id: input_select.isl_pora_dnia
            state: "tryb_spania"
          - condition: state
            entity_id: light.yl_korytarz
            state: "off"
        sequence:
        - service: scene.turn_on
          entity_id: scene.hw_tryb_red
      default:
      - service: light.turn_off
        entity_id: light.yl_korytarz
  - alias: kt_light
    mode: restart
    trigger:
    - platform: state
      entity_id: binary_sensor.ruch_kuchnia_occupancy
    action:
    - choose:
## gdy na 'on'
      - conditions: # do wieczora
        - condition: and
          conditions:
          - condition: state
            entity_id: binary_sensor.ruch_kuchnia_occupancy
            state: "on"
          - condition: state
            entity_id: group.gr_who
            state: "home"
          - condition: time
            after: "06:00:00"
            before: "23:00:00"
        sequence:
        - service: light.turn_on
          entity_id: light.ledy_w_kuchni
      - conditions: # w nocy
        - condition: and
          conditions:
          - condition: state
            entity_id: binary_sensor.ruch_kuchnia_occupancy
            state: "on"
          - condition: state
            entity_id: light.ledy_w_kuchni
            state: "off"
          - condition: state
            entity_id: light.yl_plafon1
            state: "off"
          - condition: state
            entity_id: group.gr_who
            state: "home"
          - condition: time
            after: "23:01:00"
            before: "05:59:00"
        sequence:
        - service: scene.turn_on
          entity_id: scene.plafon_tryb_red
## gdy na 'off'
      - conditions: # do wieczora
        - condition: and
          conditions:
          - condition: state
            entity_id: binary_sensor.ruch_kuchnia_occupancy
            state: "off"
          - condition: state
            entity_id: group.gr_who
            state: "home"
          - condition: time
            after: "06:00:00"
            before: "23:00:00"
        sequence:
        - service: light.turn_off
          entity_id: light.ledy_w_kuchni
      - conditions: # w nocy
        - condition: and
          conditions:
          - condition: state
            entity_id: binary_sensor.ruch_kuchnia_occupancy
            state: "off"
          - condition: state
            entity_id: light.ledy_w_kuchni
            state: "off"
          - condition: state
            entity_id: group.gr_who
            state: "home"
          - condition: time
            after: "23:01:00"
            before: "05:59:00"
        sequence:
        - service: light.turn_off
          entity_id: light.yl_plafon1
  # jeśli nie ma ruchu w kuchni - wyłącz ledy

script:
  kuchnia_poczatek_pracy:
    sequence:
    - service: light.turn_on
      data:
        entity_id: light.ledy_w_kuchni
    - service: automation.turn_off
      data:
        entity_id: automation.kt_light
  kuchnia_koniec_pracy:
    sequence:
    - service: automation.turn_on
      data:
        entity_id: automation.kt_light